/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertCustom: typeof import('./src/components/common/modals/AlertCustom.vue')['default']
    AppCustom: typeof import('./src/components/lazy/AppCustom.vue')['default']
    BookmarkIcon: typeof import('./src/components/common/icons/BookmarkIcon.vue')['default']
    Button: typeof import('primevue/button')['default']
    CabeceraPorDefecto: typeof import('./src/components/lazy/CabeceraPorDefecto.vue')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    Componente: typeof import('./src/components/Componente.vue')['default']
    ContenidoPorDefecto: typeof import('./src/components/lazy/ContenidoPorDefecto.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Form: typeof import('@p./src/components/lazy/CabeceraPorDefecto.vue
    Header: typeof import('./src/components/lazy/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/PlantillaBase.vue')['default']
    LazyComponente: typeof import('./src/components/lazy/LazyComponente.vue')['default']
    LazyCustom: typeof import('./src/components/lazy/LazyCustom.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    PlantillaBase: typeof import('./src/components/PlantillaBase.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveIcon: typeof import('./src/components/common/icons/SaveIcon.vue')['default']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    ThemeToggle: typeof import('./src/common/components/ThemeToggle.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    ToolBarFlotante: typeof import('./src/components/lazy/ToolBarFlotante.vue')['default']
    ToolBarPrincipal: typeof import('./src/components/lazy/ToolBarPrincipal.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
